//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngredientTable()
        {
            this.QuantityTables = new HashSet<QuantityTable>();
        }
    
        public int ingredientId { get; set; }
        public string ingredientsName { get; set; }
        public string unit { get; set; }
        public int quantityName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuantityTable> QuantityTables { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityTable
    {
        public int RecipieId { get; set; }
        public int ingredientId { get; set; }
        public decimal quantity { get; set; }
    
        public virtual IngredientTable IngredientTable { get; set; }
        public virtual RecipeTable RecipeTable { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecipeTable()
        {
            this.QuantityTables = new HashSet<QuantityTable>();
        }
    
        public int RecipieId { get; set; }
        public string Name { get; set; }
        public string SubmittedBy { get; set; }
        public string Category { get; set; }
        public Nullable<int> Cookingtime { get; set; }
        public int Numberofservings { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuantityTable> QuantityTables { get; set; }
    }
}
